/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    DB_MAN DBM = new DB_MAN();
    String getListSQL = "select * from memberinfo";
    String getSortListSQL = "select * from memberinfo order by no";
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
	initComponents();
	
	try {
	    DBM.dbOpen();
		getDBData(getSortListSQL);
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }
    
    
    public void resetTable(){
	int iCntRow = jTable1.getRowCount();
	
	for(int i = 0; i < iCntRow; i++){
	    if(jTable1.getValueAt(i, 0) != null){
		for(int j = 0; j < 5; j++){
		    jTable1.setValueAt(null, i, j);
		}
	    } else {
		break;
	    }
	}
    }
    
    public void getDBData(String strQuery){
	resetTable();

	int iCntRow = jTable1.getRowCount();
	
	try {
	    DBM.DB_rs = DBM.DB_stmt.executeQuery(strQuery);
	    
	    while(DBM.DB_rs.next()){
		for(int i = 0; i < jTable1.getRowCount(); i++){
		    if(jTable1.getValueAt(i, 0) == null){
			iCntRow = i;
			break;
		    }
		}
		
		String[] val = {
		    DBM.DB_rs.getString("NO"), 
		    DBM.DB_rs.getString("NAME"), 
		    DBM.DB_rs.getString("CHARGE"), 
		    DBM.DB_rs.getString("PHONE"), 
		    DBM.DB_rs.getString("GRADE")
		};
		
		for(int i = 0; i < 5; i++){
		    jTable1.setValueAt(val[i], iCntRow, i);
		}
	    }
	    
	    DBM.DB_rs.close();
	} catch(Exception e){
	    System.out.println(e);
	}
    }
    
    public String makeSQLWhere(String strQuery){
	switch(cbxSearch.getSelectedIndex()){
	    case 0 :
		strQuery += " where no = '" + tbxNo.getText() + "'";
		break;
	    case 1 :
		strQuery += " where name = '" + tbxName.getText() + "'";
		break;
	    case 2:
		strQuery += " where charge = '" + tbxCharge.getText() + "'";
		break;
	    case 3:
		strQuery += " where phone = '" + tbxPhone.getText() + "'";
		break;
	    default :
		strQuery = getSortListSQL;
		break;
	}
	
	return strQuery;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCharge = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblSQL = new javax.swing.JLabel();
        tbxNo = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        cbxSearch = new javax.swing.JComboBox<>();
        btnSelect = new javax.swing.JButton();
        tbxName = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        tbxCharge = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        tbxPhone = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        tbxSQL = new javax.swing.JTextField();
        btnExecute = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("회원 정보 관리");

        lblNo.setText("번호");

        lblName.setText("성명");

        lblCharge.setText("월정액");

        lblPhone.setText("연락처");

        lblSQL.setText("SQL문");

        lblSearch.setText("검색 기준");

        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "번호", "성명", "월정액", "연락처" }));

        btnSelect.setText("검 색");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnInsert.setText("추 가");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("수 정");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("삭 제");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("종료");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnExecute.setText("실행");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "번호", "성명", "월정액", "연락처", "등 급"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNo)
                        .addGap(30, 30, 30)
                        .addComponent(tbxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblTitle)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSQL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhone)
                                .addGap(18, 18, 18)
                                .addComponent(tbxPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCharge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExecute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNo)
                    .addComponent(tbxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch)
                    .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(tbxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCharge)
                    .addComponent(tbxCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(tbxPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSQL)
                    .addComponent(tbxSQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExecute))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
	String strSQL = makeSQLWhere(getListSQL);
	
	try {
	    DBM.dbOpen();
		DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);

		while(DBM.DB_rs.next()){
		    tbxNo.setText(DBM.DB_rs.getString("no"));
		    tbxName.setText(DBM.DB_rs.getString("name"));
		    tbxCharge.setText(DBM.DB_rs.getString("charge"));
		    tbxPhone.setText(DBM.DB_rs.getString("phone"));
		}

		DBM.DB_rs.close();
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String strSQL = "insert into memberinfo values (";
	strSQL += "'" + tbxNo.getText() + "', ";
	strSQL += "'" + tbxName.getText() + "', ";
	strSQL += "'" + tbxCharge.getText() + "', ";
	strSQL += "'" + tbxPhone.getText() + "', ";
	
	int tbxChargeValue = Integer.parseInt(tbxCharge.getText());
	
	String grade = "";
	
	if(tbxChargeValue >= 100000){
	    grade = "VIP";
	} else if(tbxChargeValue >= 50000){
	    grade = "Gold";
	} else if(tbxChargeValue < 50000){
	    grade = "Silver";
	}
	
	strSQL += "'" + grade + "')";
	
	try {
	    DBM.dbOpen();
	    
		DBM.DB_stmt.executeUpdate(strSQL);
		getDBData(getSortListSQL);
		
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
	String strSQL = "update memberinfo set ";
	strSQL += "no = '" + tbxNo.getText() + "', ";
	strSQL += "name = '" + tbxName.getText() + "', ";
	strSQL += "charge = '" + tbxCharge.getText() + "', ";
	strSQL += "phone = '" + tbxPhone.getText() + "', ";
	
	int tbxChargeValue = Integer.parseInt(tbxCharge.getText());
	
	String grade = "";
	
	if(tbxChargeValue >= 100000){
	    grade = "VIP";
	} else if(tbxChargeValue >= 50000){
	    grade = "Gold";
	} else if(tbxChargeValue < 50000){
	    grade = "Silver";
	}
	
	strSQL += "grade = '" + grade + "'";
	
	strSQL = makeSQLWhere(strSQL);
	
	try {
	    DBM.dbOpen();
	    
		DBM.DB_stmt.executeUpdate(strSQL);
		getDBData(getSortListSQL);
		
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String strSQL = "delete from memberinfo";
	strSQL = makeSQLWhere(strSQL);
	
	try {
	    DBM.dbOpen();
		DBM.DB_stmt.executeUpdate(strSQL);
		getDBData(getSortListSQL);
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
	String strSQL = tbxSQL.getText();
	
	try {
	    DBM.dbOpen();
	    
	    if(strSQL.contains("select")){
		getDBData(strSQL);
	    } else {
		DBM.DB_stmt.executeUpdate(strSQL);
		getDBData(getListSQL);
	    } 
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
	
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new MainFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxSearch;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblCharge;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSQL;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tbxCharge;
    private javax.swing.JTextField tbxName;
    private javax.swing.JTextField tbxNo;
    private javax.swing.JTextField tbxPhone;
    private javax.swing.JTextField tbxSQL;
    // End of variables declaration//GEN-END:variables
}
