/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    DB_MAN DBM = new DB_MAN();
    String strSQL = "select * from car";
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
	initComponents();
	
	try {
	    DBM.dbOpen();
	    getDBData(strSQL);
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }
    
    public void getDBData(String strQuery){
	String strOutput = "번호\t차종\t배기량\t연비\t가격\n";
	
	jTextArea1.setText(strOutput);
	
	try {
	    DBM.DB_rs = DBM.DB_stmt.executeQuery(strQuery);
	    
	    while(DBM.DB_rs.next()){
		strOutput = "";
		strOutput += DBM.DB_rs.getString("No")+"\t";
		strOutput += DBM.DB_rs.getString("Type")+"\t";
		strOutput += DBM.DB_rs.getString("Displacement")+"\t";
		strOutput += DBM.DB_rs.getString("Performance")+"\t";
		strOutput += DBM.DB_rs.getString("Price")+"\n";
		
		jTextArea1.append(strOutput);
	    }
	    
	    DBM.DB_rs.close();
	} catch(Exception e){
	    System.out.println(e);
	}
    }
    
    public String makeSQLWhere(String strQuery){
	switch(cbxSearch.getSelectedIndex()){
	    case 0 :
		strQuery += " where no = '" + tbxNo.getText() + "'";
		break;
	    case 1 :
		strQuery += " where type = '" + tbxCarType.getText() + "'";
		break;
	    case 2:
		strQuery += " where displacement = '" + tbxCC.getText() + "'";
		break;
	    case 3:
		strQuery += " where performance = '" + tbxKM.getText() + "'";
		break;
	    case 4:
		strQuery += " where price = '" + tbxPrice.getText() + "'";
		break;
	    default :
		strQuery = "select * from car";
		break;
	}
	
	return strQuery;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblCarType = new javax.swing.JLabel();
        lblCC = new javax.swing.JLabel();
        lblKM = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblSQL = new javax.swing.JLabel();
        tbxNo = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        cbxSearch = new javax.swing.JComboBox<>();
        btnSelect = new javax.swing.JButton();
        tbxCarType = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        tbxCC = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        tbxKM = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        tbxPrice = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        tbxSQL = new javax.swing.JTextField();
        btnExecute = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("자동차 정보 관리");

        lblNo.setText("번호");

        lblCarType.setText("차종");

        lblCC.setText("배기량");

        lblKM.setText("연비");

        lblPrice.setText("가격");

        lblSQL.setText("SQL문");

        lblSearch.setText("검색 기준");

        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "번호", "차종", "배기량", "연비", "가격" }));

        btnSelect.setText("검 색");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnInsert.setText("추 가");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("수 정");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("삭 제");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("종료");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnExecute.setText("실행");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNo)
                        .addGap(18, 18, 18)
                        .addComponent(tbxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrice)
                                .addGap(18, 18, 18)
                                .addComponent(tbxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSQL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbxSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKM)
                                .addGap(18, 18, 18)
                                .addComponent(tbxKM, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbxCC, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCarType)
                                .addGap(18, 18, 18)
                                .addComponent(tbxCarType, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExecute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNo)
                    .addComponent(tbxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch)
                    .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarType)
                    .addComponent(tbxCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCC)
                    .addComponent(tbxCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKM)
                    .addComponent(tbxKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(tbxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSQL)
                    .addComponent(tbxSQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExecute))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        strSQL = "select * from car";
	strSQL = makeSQLWhere(strSQL);
	
	try {
	    System.out.println(strSQL);
	    
	    DBM.dbOpen();
	    DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
	    
	    while(DBM.DB_rs.next()){
		tbxNo.setText(DBM.DB_rs.getString("no"));
		tbxCarType.setText(DBM.DB_rs.getString("type"));
		tbxCC.setText(DBM.DB_rs.getString("displacement"));
		tbxKM.setText(DBM.DB_rs.getString("performance"));
		tbxPrice.setText(DBM.DB_rs.getString("price"));
	    }
	    
	    DBM.DB_rs.close();
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        strSQL = "insert into car values (";
	strSQL += "'" + tbxNo.getText() + "', ";
	strSQL += "'" + tbxCarType.getText() + "', ";
	strSQL += "'" + tbxCC.getText() + "', ";
	strSQL += "'" + tbxKM.getText() + "', ";
	strSQL += "'" + tbxPrice.getText() + "')";
	
	try {
	    DBM.dbOpen();
	    DBM.DB_stmt.executeUpdate(strSQL);
	    strSQL = "select * from car";
	    getDBData(strSQL);
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        strSQL = "update car set ";
	strSQL += "type = '" + tbxCarType.getText() + "', ";
	strSQL += "displacement = '" + tbxCC.getText() + "', ";
	strSQL += "performance = '" + tbxKM.getText() + "', ";
	strSQL += "price = '" + tbxPrice.getText() + "' ";
	strSQL = makeSQLWhere(strSQL);
	
	try {
	    DBM.dbOpen();
	    DBM.DB_stmt.executeUpdate(strSQL);
	    strSQL = "select * from car";
	    getDBData(strSQL);
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        strSQL = "delete from car";
	strSQL = makeSQLWhere(strSQL);
	
	try {
	    DBM.dbOpen();
	    DBM.DB_stmt.executeUpdate(strSQL);
	    strSQL = "select * from car";
	    getDBData(strSQL);
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        String strData = "select * from car";
	
	strSQL = tbxSQL.getText();
	strSQL = strSQL.toLowerCase();
	
	try {
	    DBM.dbOpen();
	    
	    if(strSQL.contains("select"))
		getDBData(strSQL);
	    else
		DBM.DB_stmt.executeUpdate(strSQL);
	    
	    DBM.dbClose();
	} catch(Exception e){
	    System.out.println(e.getMessage());
	}
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new MainFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblCC;
    private javax.swing.JLabel lblCarType;
    private javax.swing.JLabel lblKM;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSQL;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tbxCC;
    private javax.swing.JTextField tbxCarType;
    private javax.swing.JTextField tbxKM;
    private javax.swing.JTextField tbxNo;
    private javax.swing.JTextField tbxPrice;
    private javax.swing.JTextField tbxSQL;
    // End of variables declaration//GEN-END:variables
}
