/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    double dResult = 0;
    double dTemp = 0;
    
    String result = "";
    String temp = "";
    String discri = "";
    String mem = "";
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupNumber = new javax.swing.ButtonGroup();
        btnGroupOperator = new javax.swing.ButtonGroup();
        btnGroupMemory = new javax.swing.ButtonGroup();
        btnGroupTextControl = new javax.swing.ButtonGroup();
        tbxInput = new javax.swing.JTextField();
        btnResult = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btn1X = new javax.swing.JButton();
        btnRemain = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnMemPlus = new javax.swing.JButton();
        btnMemClear = new javax.swing.JButton();
        btnMemRead = new javax.swing.JButton();
        btnMemSave = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("계산기");

        tbxInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tbxInput.setText("0.");

        btnResult.setText("=");
        btnGroupOperator.add(btnResult);
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnGroupOperator.add(btnPlus);
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnGroupOperator.add(btnMinus);
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btn1X.setText("1/x");
        btnGroupOperator.add(btn1X);
        btn1X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1XActionPerformed(evt);
            }
        });

        btnRemain.setText("%");
        btnGroupOperator.add(btnRemain);
        btnRemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemainActionPerformed(evt);
            }
        });

        btnSqrt.setText("sqrt");
        btnGroupOperator.add(btnSqrt);
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        btnMultiply.setText("*");
        btnGroupOperator.add(btnMultiply);
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnDivision.setText("/");
        btnGroupOperator.add(btnDivision);
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnDot.setText(".");
        btnGroupNumber.add(btnDot);
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnNum3.setText("3");
        btnGroupNumber.add(btnNum3);
        btnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum3ActionPerformed(evt);
            }
        });

        btnNum6.setText("6");
        btnGroupNumber.add(btnNum6);
        btnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum6ActionPerformed(evt);
            }
        });

        btnNum9.setText("9");
        btnGroupNumber.add(btnNum9);
        btnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum9ActionPerformed(evt);
            }
        });

        btnNum8.setText("8");
        btnGroupNumber.add(btnNum8);
        btnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum8ActionPerformed(evt);
            }
        });

        btnNum2.setText("2");
        btnGroupNumber.add(btnNum2);
        btnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum2ActionPerformed(evt);
            }
        });

        btnNum5.setText("5");
        btnGroupNumber.add(btnNum5);
        btnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum5ActionPerformed(evt);
            }
        });

        btnNum7.setText("7");
        btnGroupNumber.add(btnNum7);
        btnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum7ActionPerformed(evt);
            }
        });

        btnNum1.setText("1");
        btnGroupNumber.add(btnNum1);
        btnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum1ActionPerformed(evt);
            }
        });

        btnNum4.setText("4");
        btnGroupNumber.add(btnNum4);
        btnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum4ActionPerformed(evt);
            }
        });

        btnPlusMinus.setText("+/-");
        btnGroupNumber.add(btnPlusMinus);
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });

        btnNum0.setText("0");
        btnGroupNumber.add(btnNum0);
        btnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum0ActionPerformed(evt);
            }
        });

        btnMemPlus.setText("M+");
        btnGroupMemory.add(btnMemPlus);
        btnMemPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemPlusActionPerformed(evt);
            }
        });

        btnMemClear.setText("MC");
        btnGroupMemory.add(btnMemClear);
        btnMemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemClearActionPerformed(evt);
            }
        });

        btnMemRead.setText("MR");
        btnGroupMemory.add(btnMemRead);
        btnMemRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemReadActionPerformed(evt);
            }
        });

        btnMemSave.setText("MS");
        btnGroupMemory.add(btnMemSave);
        btnMemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemSaveActionPerformed(evt);
            }
        });

        btnBackspace.setText("Backspace");
        btnGroupTextControl.add(btnBackspace);
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        btnDelete.setText("CE");
        btnGroupTextControl.add(btnDelete);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("C");
        btnGroupTextControl.add(btnClear);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(tbxInput)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMemRead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMemSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMemPlus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnMemClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNum5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn1X, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tbxInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNum7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDivision, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMemClear, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMemRead, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRemain, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMemSave, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMinus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn1X, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMemPlus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNum0, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDot, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPlus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnResult, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appendNumber(int num){
	if(num == 0){
	    if(!temp.equals("0"))
		temp += num;
	} else if(temp.equals("0")){
	    temp = "";
	    temp += num;
	} else if(num != 0) {
	    temp += num;
	}
	
	tbxInput.setText(temp);
    }
    
    private void btnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum0ActionPerformed
        appendNumber(0);
    }//GEN-LAST:event_btnNum0ActionPerformed

    private void btnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum1ActionPerformed
        appendNumber(1);
    }//GEN-LAST:event_btnNum1ActionPerformed

    private void btnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum2ActionPerformed
        appendNumber(2);
    }//GEN-LAST:event_btnNum2ActionPerformed

    private void btnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum3ActionPerformed
        appendNumber(3);
    }//GEN-LAST:event_btnNum3ActionPerformed

    private void btnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum4ActionPerformed
        appendNumber(4);
    }//GEN-LAST:event_btnNum4ActionPerformed

    private void btnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum5ActionPerformed
        appendNumber(5);
    }//GEN-LAST:event_btnNum5ActionPerformed

    private void btnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum6ActionPerformed
        appendNumber(6);
    }//GEN-LAST:event_btnNum6ActionPerformed

    private void btnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum7ActionPerformed
        appendNumber(7);
    }//GEN-LAST:event_btnNum7ActionPerformed

    private void btnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum8ActionPerformed
        appendNumber(8);
    }//GEN-LAST:event_btnNum8ActionPerformed

    private void btnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum9ActionPerformed
        appendNumber(9);
    }//GEN-LAST:event_btnNum9ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        dResult = 0;
	dTemp = 0;

	result = "";
	temp = "";
	discri = "";
	
	tbxInput.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        temp = "";
	
	tbxInput.setText(temp);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        String data = temp.substring(0, temp.length() - 1);
	temp = data;
	
	tbxInput.setText(temp);
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        dTemp = Double.valueOf(temp);
	
	if(dResult == 0){
           dResult = dTemp;
	} else {
           dResult += dTemp;
	}
	
	result = String.valueOf(dResult);
       
	tbxInput.setText(result);
       
	dTemp = 0;
	temp = "";
	discri = "+";
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        dTemp = Double.valueOf(temp);
       
       if(dResult == 0){
           dResult = dTemp;
       } else {
           dResult -= dTemp;
       }
       
       result = String.valueOf(dResult);
       
       tbxInput.setText(result);
       
       dTemp = 0;
       temp = "";
       discri = "-";
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        dTemp = Double.valueOf(temp);
       
       if(dResult == 0){
           dResult = dTemp;
       } else {
           dResult *= dTemp;
       }
       
       result = String.valueOf(dResult);
       
       tbxInput.setText(result);
       
       dTemp = 0;
       temp = "";
       discri = "*";
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        dTemp = Double.valueOf(temp);
       
       if(dResult == 0){
           dResult = dTemp;
       } else {
           dResult /= dTemp;
       }
       
       result = String.valueOf(dResult);
       
       tbxInput.setText(result);
       
       dTemp = 0;
       temp = "";
       discri = "/";
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        dTemp = Double.valueOf(temp);
        dResult = Math.sqrt(dTemp);
        result = String.valueOf(dResult);
	
        tbxInput.setText(result);
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnRemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemainActionPerformed
        dTemp = Double.valueOf(temp);
       
       if(dResult == 0){
           dResult = dTemp;
       } else {
           dResult %= dTemp;
       }
       
       result = String.valueOf(dResult);
       
       tbxInput.setText(result);
       
       dTemp = 0;
       temp = "";
       discri = "%";
    }//GEN-LAST:event_btnRemainActionPerformed

    private void btn1XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1XActionPerformed
        dTemp = Double.valueOf(temp);
        
        if(dTemp != 0){
            dResult = 1 / dTemp;
            
            result = String.valueOf(dResult);
            tbxInput.setText(result);
        }
        else{
            tbxInput.setText("0으로 나눌 수 없습니다.");
        }
        
        temp = "";
        dTemp = 0;
    }//GEN-LAST:event_btn1XActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        dTemp = Double.parseDouble(temp);
        
	switch (discri) {
	    case "+":
		dTemp = Double.valueOf(temp);
		dResult += dTemp;
	    break;
	    case "-":
		dResult -= dTemp;
	    break;
	    case "*":
		dResult *= dTemp;
	    break;
	    case "/":
		dResult /= dTemp;
	    break;
	    case "%":
		dResult %= dTemp;
	    break;
	}
            
	result = String.valueOf(dResult);
       
	tbxInput.setText(result);
	discri = "";
    }//GEN-LAST:event_btnResultActionPerformed

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusMinusActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        temp += ".";
        
        tbxInput.setText(temp);
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnMemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemClearActionPerformed
        mem = "";
        jLabel1.setText(mem);
    }//GEN-LAST:event_btnMemClearActionPerformed

    private void btnMemReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemReadActionPerformed
        tbxInput.setText(mem);
        temp = mem;
    }//GEN-LAST:event_btnMemReadActionPerformed

    private void btnMemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemSaveActionPerformed
        mem = temp;
        jLabel1.setText(mem);
    }//GEN-LAST:event_btnMemSaveActionPerformed

    private void btnMemPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemPlusActionPerformed
        dTemp = Double.valueOf(temp);
        dResult = dTemp + Double.valueOf(mem);
        
        result = String.valueOf(dResult);
        temp = result;
        tbxInput.setText(result);
    }//GEN-LAST:event_btnMemPlusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new MainFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1X;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDot;
    private javax.swing.ButtonGroup btnGroupMemory;
    private javax.swing.ButtonGroup btnGroupNumber;
    private javax.swing.ButtonGroup btnGroupOperator;
    private javax.swing.ButtonGroup btnGroupTextControl;
    private javax.swing.JButton btnMemClear;
    private javax.swing.JButton btnMemPlus;
    private javax.swing.JButton btnMemRead;
    private javax.swing.JButton btnMemSave;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnRemain;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tbxInput;
    // End of variables declaration//GEN-END:variables
}
